INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les grands singes', 'monkey.jpg', '1');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ("Les animaux de l'océan", 'whale.jpg', '1');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les oiseaux', 'bird.jpg', '1');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les animaux de la jungle', 'jungle.jpg', '1');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les félins', 'lion.jpg', '1');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les amphibiens', 'frog.jpg', '1');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les reptiles', 'lezard.jpg', '1');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les canidés', 'dog.jpg', '1');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les insectes', 'butterfly.jpg', '1');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les crustacés', 'crab.jpg', '1');

INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les os', 'bones.jpg', '2');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les muscles', 'muscle.jpg', '2');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les cheveux', 'hairs.jpg', '2');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le visage', 'face.jpg', '2');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les sens', 'senses.jpg', '2');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le cerveau', 'brain.jpg', '2');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le sang', 'blood.jpg', '2');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le système nerveux', 'nerves.jpg', '2');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le coeur', 'heart.jpg', '2');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les maladies', 'virus.jpg', '2');

INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La télévision', 'tv.jpg', '3');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La radio', 'radio.jpg', '3');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Youtube', 'youtube.jpg', '3');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les émissions de télévision', 'tvshow.jpg', '3');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les stars des réseaux', 'starinsta.jpg', '3');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les réseaux sociaux', 'socialmedia.jpg', '3');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les icônes de la télévision française', 'vip.jpg', '3');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Internet', 'google.jpg', '3');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La presse écrite', 'newpaper.jpg', '3');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le sport dans les médias', 'sportmedia.jpg', '3');

INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La Terre', 'earth.jpg', '4');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ("L'astronomie", 'astronomy.jpg', '4');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La chimie', 'chemistry.jpg', '4');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les sciences sociales', 'social.jpg', '4');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le climat', 'climat.jpg', '4');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les ordinateurs', 'computer.jpg', '4');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ("L'économie", 'economy.jpg', '4');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les découvertes scientifiques', 'compass.jpg', '4');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les scientifiques', 'einstein.jpg', '4');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les mathématiques', 'maths.jpg', '4');

INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les rois de France', 'frenchkings.jpg', '5');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les empires', 'empire.jpg', '5');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les vikings', 'vikings.jpg', '5');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La colonisation', 'colonial.jpg', '5');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La Guerre Froide', 'coldwar.jpg', '5');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La Première Guerre mondiale', 'ww1.jpg', '5');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La Seconde Guerre mondiale', 'ww2.jpg', '5');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La Révolution française', 'revolution.jpg', '5');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La révolution industrielle', 'industry.jpg', '5');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La Renaissance', 'renaissance.jpg', '5');

INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les frontières insolites', 'border.jpg', '6');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les continents', 'continent.jpg', '6');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les capitales', 'capitale.jpg', '6');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les fleuves', 'river.jpg', '6');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les états américains', 'usa.jpg', '6');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les volcans', 'volcanos.jpg', '6');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les pôles', 'pole.jpg', '6');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les montagnes célèbres', 'rushmore.jpg', '6');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les monuments', 'monument.jpg', '6');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les peuples du monde', 'people.jpg', '6');

INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les spécialités françaises', 'escargot.jpg', '7');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les épices', 'spices.jpg', '7');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les pâtisseries', 'dessert.jpg', '7');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les vins', 'wine.jpg', '7');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les fruits', 'fruits.jpg', '7');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les légumes', 'veget.jpg', '7');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les champignons', 'mushrooms.jpg', '7');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les cocktails', 'cocktail.jpg', '7');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les plats de Noël', 'christmas.jpg', '7');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les spécialités mondiales', 'pizza.jpg', '7');

INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les films Disney', 'disney.jpg', '8');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les réalisateurs célèbres', 'director.jpg', '8');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ("L'univers Marvel", 'marvel.jpg', '8');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le festival de Cannes', 'cannes.jpg', '8');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La cérérmonie des Oscars', 'oscars.jpg', '8');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Game of Thrones', 'got.jpg', '8');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Breaking Bad', 'breakingbad.jpg', '8');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les acteurs célèbres', 'actor.jpg', '8');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les actrices célèbres', 'actress.jpg', '8');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les biopics', 'biopic.jpg', '8');

INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les grands clubs de foot européens', 'stadium.jpg', '9');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La NBA', 'nba.jpg', '9');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les stars du tennis', 'tennis.jpg', '9');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le Superbowl', 'superbowl.jpg', '9');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ("Les JO d'été", 'josummer.jpg', '9');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ("Les JO d'hiver", 'jowinter.jpg', '9');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les plus grands athlètes', 'athletes.jpg', '9');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les icônes féminines', 'womansport.jpg', '9');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les records sportifs', 'records.jpg', '9');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La coupe du monde de football', 'worldcup.jpg', '9');

INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les lois', 'justice.jpg', '10');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La bourse', 'bourse.jpg', '10');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Le Coronavirus', 'corona.jpg', '10');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les grands mouvements sociaux', 'manif.jpg', '10');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Statistiques', 'stats.jpg', '10');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ("L'écologie", 'eco.jpg', '10');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les religions', 'religion.jpg', '10');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('La sexualité', 'sexe.jpg', '10');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les coutumes', 'customs.jpg', '10');
INSERT INTO quiz (nameQuiz, imageQuiz, idCategory) VALUES ('Les présidents français', 'france.jpg', '10');
